### PR TITLE
add terraform for deploying eks

### PR DESCRIPTION
**Pull request by ovaleanu**

### CODE REVIEW

**Comment by ovaleanu** [comment]
LGTM!

**Comment by vfarcic** [comment]
The key is in the README.md file in this repo. Can you modify it?

**Comment by abangser** [comment]
What do you mean by key @vfarcic?

I ask because I just split the original readme up to point at this. Is that what you meant?

Happy for that split to be revisited, I did it quickly to get my team clarity as they will work on this a bit today.

**Comment by vfarcic** [comment]
My bad. I did not see those changes Abby. I get a notification about the pr
but not of Direct commits. It's all good. The changes you did is what I
wanted us to do.

**Comment by abangser** [comment]
Awesome. I actually did update them a bit more as I made some assumptions that weren't right. The big missing part right now is the automation from terraform output -> env vars people can use. @ovaleanu do you have suggested commands for this?

**Comment by abangser** [comment]
> I get a notification about the pr but not of Direct commits.

Lemme know if you prefer we go through PRs even if it is just for your notifications. Happy to do that!

**Comment by vfarcic** [comment]
PRs are easier to keep track on but direct commits should be okay as well. It's only a few of us.

**Pull request merged**
